import Foundation

/// A type that represents the typed outputs of a CloudFormation stack.
///
/// Conforming types are generated by the `ContainerCodeGen` build plugin
/// from CloudFormation template JSON files. Each type embeds:
/// - The template filename (relative to Resources/)
/// - The required LocalStack services (inferred from resource types)
/// - The expected output keys from the template's `Outputs` section
///
/// At runtime, raw key-value outputs from `DescribeStacks` are validated
/// and stored as simple properties — no `try` needed for property access.
public protocol StackOutputs: Sendable {
    /// The template filename (relative to Resources/), embedded by the build plugin.
    static var templateFileName: String { get }

    /// Services inferred from the template's resource types, always including "cloudformation".
    static var requiredServices: [String] { get }

    /// The output keys expected from the stack.
    static var expectedOutputKeys: [String] { get }

    /// Raw key-value outputs from DescribeStacks.
    var rawOutputs: [String: String] { get }

    /// Validates all expected keys are present; throws ``StackOutputError/missingOutput(key:availableKeys:)`` if not.
    init(rawOutputs: [String: String]) throws
}

extension StackOutputs {
    /// Resolves the template path relative to the caller's source file.
    ///
    /// Assumes the template lives in a `Resources/` directory alongside the
    /// calling source file. Pass `#filePath` from the call site.
    public static func templatePath(
        relativeTo filePath: String
    ) -> String {
        URL(fileURLWithPath: filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Resources")
            .appendingPathComponent(templateFileName)
            .path
    }
}
