import Foundation
import LocalContainers

/// A type that represents the typed outputs of a CloudFormation stack.
///
/// Conforming types are generated by the `ContainerCodeGen` build plugin
/// from CloudFormation templates listed in `.local-containers/codegen.json`.
/// Each generated type embeds:
/// - A `templatePath` pointing at a staged copy of the source template,
///   derived from `#filePath` at build time so it's stable across test runs.
/// - The required LocalStack services (inferred from resource types).
/// - The expected output keys from the template's `Outputs` section.
///
/// At runtime, raw key-value outputs from `DescribeStacks` are validated
/// and stored as simple properties — no `try` needed for property access.
public protocol StackOutputs: Sendable {
    /// Absolute path to the staged CloudFormation template for this stack.
    ///
    /// Points at a copy of the source template that the build plugin writes
    /// into its own work directory alongside the generated source file. The
    /// generated struct computes this path via `#filePath`, so it resolves
    /// correctly for any test run built on the same machine.
    static var templatePath: String { get }

    /// Services inferred from the template's resource types, always including "cloudformation".
    static var requiredServices: [String] { get }

    /// The output keys expected from the stack.
    static var expectedOutputKeys: [String] { get }

    /// Raw key-value outputs from DescribeStacks.
    var rawOutputs: [String: String] { get }

    /// Validates all expected keys are present; throws ``StackOutputError/missingOutput(key:availableKeys:)`` if not.
    init(rawOutputs: [String: String]) throws
}

extension StackOutputs {
    /// The AWS endpoint URL for the LocalStack container backing this stack.
    ///
    /// Returns a URL appropriate for the current scope:
    /// - In test scope (the default): a host-relative URL using LocalStack's
    ///   public hostname + HTTPS, suitable for AWS SDK clients and tools like
    ///   `cdklocal` that validate TLS against the published certificate.
    /// - Inside a `@DockerfileContainer(environment:)` provider closure (where
    ///   ``ContainerExecutionScope/isInSiblingEnvironmentResolution`` is set
    ///   by the trait): a URL using the LocalStack container's bridge gateway
    ///   IP, reachable from sibling containers on the same Docker bridge.
    ///
    /// Both URL forms are populated into ``rawOutputs`` by
    /// ``CloudFormationSetup/fetchOutputs(from:)``; this property picks the
    /// right one based on caller scope, so user code can write
    /// `c.aws.awsEndpoint` everywhere without thinking about which URL form
    /// is reachable from where.
    public var awsEndpoint: String {
        let key =
            ContainerExecutionScope.isInSiblingEnvironmentResolution
            ? "_awsEndpointForSiblings"
            : "_awsEndpoint"
        guard let endpoint = rawOutputs[key] else {
            preconditionFailure(
                "No AWS endpoint — is this used inside a ContainerTrait scope?"
            )
        }
        return endpoint
    }
}
