import LocalContainers

/// A resolved view of a service container's network identity, suitable for
/// use directly in test code.
///
/// Constructed by the trait/macro machinery from a ``RunningContainer`` after
/// the container has started and its ports have been resolved. End-users
/// receive a ``ServiceEndpoint`` from the property generated by the
/// `@DockerfileContainer` macro and use it to drive HTTP/RPC traffic at the
/// running service.
public struct ServiceEndpoint: Sendable {
    /// The host address to connect to (typically `"127.0.0.1"`).
    public let host: String

    /// All resolved port mappings on the underlying container.
    public let ports: [ResolvedPortMapping]

    public init(host: String, ports: [ResolvedPortMapping]) {
        self.host = host
        self.ports = ports
    }

    public init(from container: RunningContainer) {
        self.init(host: container.host, ports: container.ports)
    }

    /// The host port mapped to the given container port.
    ///
    /// - Throws: ``ContainerError/portNotFound(containerPort:)`` if no mapping exists.
    public func port(_ containerPort: UInt16) throws -> UInt16 {
        guard let mapping = ports.first(where: { $0.containerPort == containerPort }) else {
            throw ContainerError.portNotFound(containerPort: containerPort)
        }
        return mapping.hostPort
    }

    /// Convenience URL for services that expose a single TCP port.
    ///
    /// Returns `"http://<host>:<port>"` when exactly one TCP port is exposed.
    /// For multi-port services this traps — use ``port(_:)`` to disambiguate.
    public var baseURL: String {
        let tcpPorts = ports.filter { $0.protocol == .tcp }
        guard let only = tcpPorts.first, tcpPorts.count == 1 else {
            preconditionFailure(
                "ServiceEndpoint.baseURL is only valid when exactly one TCP port is exposed; "
                    + "this endpoint has \(tcpPorts.count) TCP ports — use port(_:) to disambiguate."
            )
        }
        return "http://\(host):\(only.hostPort)"
    }
}
